package com.ycy.center.dao.entity;

import java.io.Serializable;

public class YcyTable implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ycy_table.id
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ycy_table.name
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ycy_table.num
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ycy_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ycy_table.id
     *
     * @return the value of ycy_table.id
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ycy_table.id
     *
     * @param id the value for ycy_table.id
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ycy_table.name
     *
     * @return the value of ycy_table.name
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ycy_table.name
     *
     * @param name the value for ycy_table.name
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ycy_table.num
     *
     * @return the value of ycy_table.num
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ycy_table.num
     *
     * @param num the value for ycy_table.num
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ycy_table
     *
     * @mbggenerated Wed Jul 20 01:22:03 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", num=").append(num);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}